### ISSUE TITLE
Visualize thresholds when plotting MetricValueWithThresholds

### ISSUE THREAD

**Issue by kennysong** [citadel-ai/langcheck#38]
When plotting a MetricValueWithThreshold value like `(toxicity_values > 0.5).scatter()`, we should draw a vertical line in the chart where the threshold is.

We could do this for the double scatter plot (`langcheck.plot.scatter(toxicity_values > 0.5, sentiment_values > 0.5)`) and the histogram as well (`(toxicity_values > 0.5).histogram()`).

**Comment by Vela-zz** [comment]
@kennysong  Hi Song, I'm trying to add code for this feature now, but before I  complete it, I want to ask is there any plan to support more Filter Syntax in the future？

```
toxicity_values > 0.5 and toxicity_values < 0.7
#
toxicity_values < 0.3 | toxicity_values > 0.7

```
I think it is also a new feature that can be added.

**Comment by kennysong** [comment]
Hi @Vela-zz, thanks for the PR! I don't think we're planning to support those multi-condition thresholds right now, so we can keep your PR focused on the existing binary threshold case.

If you're looking for other issues to work on, happy to chat more [on Discord](https://discord.com/invite/Bkndx9RXqw)!

cc @yosukehigashi
