### ISSUE TITLE
Show tqdm progress bar for metric functions

### ISSUE THREAD

**Issue by kennysong** [citadel-ai/langcheck#4]
I just ran fluency for a list of 100 strings and it was fairly slow. Showing a progress indicator would be nice.

**Comment by ThanhChinhBK** [comment]
hello, I'm interested in this project, can I handle this issue?

**Comment by liwii** [comment]
Thanks for your interest, it would be definitely helpful if you could tackle this!

Let me set you as the assignee for now. Feel free to write them down if you have any questions/opinions.

Again, thanks a lot!!

**Comment by kennysong** [comment]
Btw, we just created a Discord if you want to chat about this feature with our team!

https://discord.gg/Aq4nr4n6
